## Feature Engineering

### Realisation

I realised that I have to feature engineer before scaling, since I didn't realise that scaling caused for my data to be placed within a range from 0-1. So, I have decided to save my initial wrangled data and merge it with the new features that I'll create and scale here.

### Import dependencies

In [1]:
import pandas as pd

### Store CSV as variable

In [2]:
data_frame = pd.read_csv("2.2.1.engineering_val_ds.csv")

### Remove Duplicates and Outliers again

In [3]:
# Remove Duplicates
data_frame = data_frame.drop_duplicates()
data_frame.duplicated().sum()

np.int64(0)

In [4]:
#Remove outliers
# Identify IQR for kills_total to highlight outliers
Q1 = data_frame["kills_total"].quantile(0.25)
Q3 = data_frame["kills_total"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a kills_total above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["kills_total"] >= Q1 - 1.5 * IQR)
    & (data_frame["kills_total"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for wins_total to highlight outliers
Q1 = data_frame["wins_total"].quantile(0.25)
Q3 = data_frame["wins_total"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a wins_total above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["wins_total"] >= Q1 - 1.5 * IQR)
    & (data_frame["wins_total"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for matchs_played to highlight outliers
Q1 = data_frame["matchs_played"].quantile(0.25)
Q3 = data_frame["matchs_played"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a matchs_played above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["matchs_played"] >= Q1 - 1.5 * IQR)
    & (data_frame["matchs_played"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for k/d to highlight outliers
Q1 = data_frame["k/d"].quantile(0.25)
Q3 = data_frame["k/d"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a k/d above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["k/d"] >= Q1 - 1.5 * IQR) & (data_frame["k/d"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for dmg/rnd to highlight outliers
Q1 = data_frame["dmg/rnd"].quantile(0.25)
Q3 = data_frame["dmg/rnd"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a dmg/rnd above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["dmg/rnd"] >= Q1 - 1.5 * IQR)
    & (data_frame["dmg/rnd"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for win% to highlight outliers
Q1 = data_frame["win%"].quantile(0.25)
Q3 = data_frame["win%"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a win% above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["win%"] >= Q1 - 1.5 * IQR) & (data_frame["win%"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for headshot_% to highlight outliers
Q1 = data_frame["headshot_%"].quantile(0.25)
Q3 = data_frame["headshot_%"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a headshot_% above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["headshot_%"] >= Q1 - 1.5 * IQR)
    & (data_frame["headshot_%"] <= Q3 + 1.5 * IQR)
]

# Identify IQR for avg_kill_per_rnd to highlight outliers
Q1 = data_frame["avg_kill_per_rnd"].quantile(0.25)
Q3 = data_frame["avg_kill_per_rnd"].quantile(0.75)
IQR = Q3 - Q1
print(
    f"Outliers are a avg_kill_per_rnd above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}"
)
# Adjust range to IQR
data_frame = data_frame[
    (data_frame["avg_kill_per_rnd"] >= Q1 - 1.5 * IQR)
    & (data_frame["avg_kill_per_rnd"] <= Q3 + 1.5 * IQR)
]

Outliers are a kills_total above 27350.38 or below -12628.62
Outliers are a wins_total above 747.75 or below -326.25
Outliers are a matchs_played above 1437.50 or below -622.50
Outliers are a k/d above 1.54 or below 0.58
Outliers are a dmg/rnd above 193.15 or below 91.75
Outliers are a win% above 73.90 or below 29.10
Outliers are a headshot_% above 29.73 or below 3.12
Outliers are a avg_kill_per_rnd above 0.95 or below 0.55

### Begin Feature Engineering

This section requires domain specific knowledge and the ability to understand why I am combining specific features which will be explained as I develop them. The main goal is to create a "Performance" feature amongst other minor ones such as "Experience" if I have to. This will be compared against the target 'win%' to hopefully simplify the algorithm also allowing to me test different models beyond just multi-feature linear regression.

I'll start by combining `k/d` and `dmg/rnd` to create an amplified number.

In [20]:
# Create dmg_indicator Feature
data_frame['dmg_indicator'] = (data_frame['k/d'] * data_frame["dmg/rnd"]).round(2)

# Create consistency Feature
data_frame["consistency"] = data_frame["wins_total"] / data_frame["matchs_played"]

# Create performance feature based off of dmg_indicator and consistency respective to matchs_played
data_frame["performance"] = (
    data_frame["dmg_indicator"]
    * data_frame["consistency"]
) * 10

# Create skill feature
data_frame['skill'] = (data_frame['headshot_%'] * data_frame['avg_kill_per_rnd'])


data_frame.describe()

,win%,k/d,dmg/rnd,matchs_played,headshot_%,wins_total,kills_total,avg_kill_per_rnd,dmg_indicator,performance,skill,consistency
count,421.000000,421.000000,421.000000,421.000000,421.000000,421.000000,421.00000,421.000000,421.000000,421.000000,421.000000,421.000000
mean,51.347506,1.056580,143.609264,467.444181,16.734204,232.311164,7185.32304,0.737767,153.960903,761.075424,12.488812,0.493491
std,8.069512,0.153938,17.000137,344.655742,4.525138,171.130932,5389.74433,0.084367,38.548949,204.219816,4.125850,0.034674
min,30.800000,0.590000,94.800000,6.000000,7.700000,2.000000,77.00000,0.600000,63.520000,303.854214,4.980000,0.310345
25%,46.200000,0.950000,131.200000,202.000000,13.400000,100.000000,2887.00000,0.700000,127.890000,633.078947,9.310000,0.480315
50%,51.100000,1.050000,145.000000,389.000000,16.100000,195.000000,5922.00000,0.700000,152.540000,749.090323,12.080000,0.495487
75%,56.500000,1.150000,154.600000,675.000000,19.700000,331.000000,10617.00000,0.800000,177.840000,877.793103,15.260000,0.511161
max,73.300000,1.500000,190.100000,1417.000000,29.600000,713.000000,23055.00000,0.900000,270.560000,1477.440000,24.570000,0.600000

### Remove outliers for new features

I adapted the previous structure to a loop to save space and make code more comprehensible. I would fix the code in data_wrangling although I think its best that I show I've made this development so I'll leave it.

In [22]:
features = ['performance', 'consistency', 'skill', 'dmg_indicator']

for feature in features:
    Q1 = data_frame[feature].quantile(0.25)
    Q3 = data_frame[feature].quantile(0.75)
    IQR = Q3 - Q1
    print(f"Outliers for {feature} are above {(Q3 + IQR * 1.5):.2f} or below {(Q1 - IQR * 1.5):.2f}")
    data_frame = data_frame[
        (data_frame[feature] >= Q1 - 1.5 * IQR)
        & (data_frame[feature] <= Q3 + 1.5 * IQR)
    ]

data_frame.describe()

Outliers for performance are above 1218.68 or below 287.91
Outliers for consistency are above 0.55 or below 0.44
Outliers for skill are above 23.25 or below 1.15
Outliers for dmg_indicator are above 240.71 or below 60.16

,win%,k/d,dmg/rnd,matchs_played,headshot_%,wins_total,kills_total,avg_kill_per_rnd,dmg_indicator,performance,skill,consistency
count,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000
mean,51.529570,1.045538,142.431452,504.526882,16.672581,250.736559,7725.612903,0.734946,150.755887,748.835880,12.367688,0.496773
std,7.790646,0.139547,15.777409,342.947085,4.354773,170.038970,5372.360290,0.081192,34.442412,173.335018,3.873497,0.020658
min,32.000000,0.590000,94.800000,6.000000,7.700000,3.000000,89.000000,0.600000,63.520000,303.854214,4.980000,0.441558
25%,46.475000,0.950000,131.200000,247.500000,13.500000,120.750000,3563.000000,0.700000,127.862500,636.124150,9.440000,0.482489
50%,51.150000,1.050000,144.250000,424.000000,16.200000,211.000000,6288.000000,0.700000,150.140000,747.821058,12.020000,0.496063
75%,56.500000,1.140000,153.625000,720.750000,19.550000,357.250000,11001.500000,0.800000,173.000000,868.207387,14.965000,0.510361
max,73.300000,1.400000,184.500000,1417.000000,28.200000,713.000000,23055.000000,0.900000,238.520000,1188.457554,22.680000,0.548673

### Scale new feature

In [ ]:
features = ["performance", "consistency", "skill", "dmg_indicator"]
MAX_v = [1250, 1, 25, 300]
MIN_v = [200, 0, 0, 0]

i = 0

for feature in features:
    data_frame[feature] = (data_frame[feature] - MIN_v) / (
    MAX_v - MIN_v)